{{- if .Values.argocd.enabled }}
{{- $fullname := include "proxy-server.fullname" . }}
{{- $serverPort := .Values.service.internalPort }}
{{- $releaseNs := .Release.Namespace }}
{{- $tlsEnabled := .Values.tls.enabled }}
{{- $scheme := ternary "https" "http" $tlsEnabled }}
{{- range .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-cluster-{{ .id }}
  namespace: {{ $.Values.argocd.namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- include "proxy-server.labels" $ | nindent 4 }}
type: Opaque
stringData:
  name: {{ .id }}
  server: "{{ $scheme }}://{{ $fullname }}-internal.{{ $releaseNs }}.svc:{{ $serverPort }}/tunnel/{{ .id }}"
  config: |
    {
      "tlsClientConfig": {
        {{- if not $tlsEnabled }}
        "insecure": true
        {{- else }}
        "insecure": false
        {{- if $.Values.argocd.caData }}
        ,"caData": {{ $.Values.argocd.caData | quote }}
        {{- end }}
        {{- if and $.Values.argocd.clientCertData $.Values.argocd.clientKeyData }}
        ,"certData": {{ $.Values.argocd.clientCertData | quote }}
        ,"keyData": {{ $.Values.argocd.clientKeyData | quote }}
        {{- end }}
        {{- end }}
      }
    }
{{- end }}
{{- end }}
