{{- if .Values.argocd.enabled }}
{{- $fullname := include "proxy-server.fullname" . }}
{{- $serverPort := .Values.service.port }}
{{- $releaseNs := .Release.Namespace }}
{{- $proxyToken := .Values.proxyToken }}
{{- range .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-cluster-{{ .id }}
  namespace: {{ $.Values.argocd.namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- include "proxy-server.labels" $ | nindent 4 }}
type: Opaque
stringData:
  name: {{ .id }}
  server: "http://{{ $fullname }}.{{ $releaseNs }}.svc:{{ $serverPort }}/tunnel/{{ .id }}"
  config: |
    {
      {{- if $proxyToken }}
      "bearerToken": {{ $proxyToken | quote }},
      {{- end }}
      "tlsClientConfig": {
        "insecure": true
      }
    }
{{- end }}
{{- end }}
