{{- if and .Values.proxyToken (not .Values.existingProxyTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-server.fullname" . }}-proxy-token
  labels:
    {{- include "proxy-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxy-token: {{ .Values.proxyToken | quote }}
{{- end }}
