{{- if and .Values.gateway.enabled (eq .Values.gateway.tlsMode "Passthrough") -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "proxy-server.fullname" . }}
  labels:
    {{- include "proxy-server.labels" . | nindent 4 }}
  {{- with .Values.gateway.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- if .Values.gateway.create }}
    - name: {{ include "proxy-server.fullname" . }}
      sectionName: tls
    {{- else }}
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- if or .Values.gateway.hostname .Values.gateway.hostnames }}
  hostnames:
    {{- with .Values.gateway.hostname }}
    - {{ . | quote }}
    {{- end }}
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "proxy-server.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
