{{- if and .Values.token (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-agent.fullname" . }}-token
  labels:
    {{- include "proxy-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token | quote }}
{{- end }}
